### ISSUE TITLE
Mute state

### ISSUE THREAD

**Issue by cgrace70** [frgnca/AudioDeviceCmdlets#10]
Is there a way to determine the state of mute/unmute for the default audio device?   I know you can set it, but I want to determine if it is muted or not.

**Comment by cdhunt** [comment]
Not currently.

**Comment by cdhunt** [comment]
@cgrace70 It's not obvious, but you can get and set mute state manually.

``` powershell
(Get-DefaultAudioDevice).Device.AudioEndpointVolume.Mute

(Get-DefaultAudioDevice).Device.AudioEndpointVolume.Mute = $true
```

**Comment by frgnca** [comment]
I have created pull request #13 (Get-DefaultAudioDeviceMute) which should resolve this enhancement request. It returns a value of true or false.

**Comment by cdhunt** [comment]
Closing thanks to @frgnca contribution.
