### ISSUE TITLE
Script block not working for 'Set-DefaultAudioDevice'

### ISSUE THREAD

**Issue by TheEngineerGuy** [frgnca/AudioDeviceCmdlets#15]
"Get-AudioDeviceList | Where-Object {$_.DeviceFriendlyname -like '*SAMSUNG*'} | foreach {$_.Index}" returns value 4. 

However, when I run "Set-DefaultAudioDevice {Get-AudioDeviceList | Where-Object {$_.DeviceFriendlyname -like '*SAMSUNG*'} | foreach {$_.Index}}", the index 0 gets set.

Copy paste from PowerShell window is as below:

PS C:\Windows\system32> Get-AudioDeviceList | Where-Object {$_.DeviceFriendlyname -like '*SAMSUNG*'} | foreach {$_.Index}
4
PS C:\Windows\system32> Set-DefaultAudioDevice {Get-AudioDeviceList | Where-Object {$_.DeviceFriendlyname -like '*SAMSUNG*'} | foreach {$_.Index}}

Index DeviceFriendlyname                       Device
----- ------------------                       ------
    0 Speakers (Realtek High Definition Audio) CoreAudioApi.MMDevice

**Comment by TheEngineerGuy** [comment]
Got it change {} to ()

Command that works "Set-DefaultAudioDevice (Get-AudioDeviceList | Where-Object {$_.DeviceFriendlyname -like '*SAMSUNG*'} | foreach {$_.Index})"

**Comment by cdhunt** [comment]
👍
