### ISSUE TITLE
Default Micophone

### ISSUE THREAD

**Issue by stevemenke** [frgnca/AudioDeviceCmdlets#16]
Do you have anything similar for input devices / microphones?

**Comment by frgnca** [comment]
Does this work for you? https://github.com/frgnca/AudioDeviceCmdlets

**Comment by cdhunt** [comment]
@frgnca Would you like to formally take over this project? If you PR your changes I can transfer the original project to you.

https://help.github.com/articles/about-repository-transfers/

**Comment by frgnca** [comment]
Yes, I would be interested. Thank you for offering this. I've created the pull request #17

**Comment by cdhunt** [comment]
@frgnca If you rename/remove your existing repo, I can finalize the transfer.

**Comment by frgnca** [comment]
@cdhunt I have renamed my fork from AudioDeviceCmdlets to AudioDeviceCmdlets-renamed. Don't hesitate to tell me if more needs to be done on my side. First time doing this.

**Comment by cdhunt** [comment]
@frgnca Looks yours has to be removed. GitHub won't let me transfer if you have any repo that has a relationship fo the repo being transferred. (cyclical references I suppose)

**Comment by frgnca** [comment]
@cdhunt My repository "frgnca/AudioDeviceCmdlets-renamed" was successfully deleted. Sorry for the late reply.

**Comment by frgnca** [comment]
While pointing out the fact that we organized this on an issue titled "Default Micophone", I would like to thank you again @cdhunt and confirm the transfert was successful.
