### ISSUE TITLE
Set default communication device without setting default audio device

### ISSUE THREAD

**Issue by torygreco** [frgnca/AudioDeviceCmdlets#19]
Hi, thank you for continuing this project! I use it all the time. My one suggestion to improve it would be to add functionality allowing users to set the default communications device without setting the default audio device. 

For example, if you right click an audio device in the sounds menu you have two options:
Set Default Device
Set Default Communications Device

If I use Set-AudioDevice it sets the selected audio device as both the defualt device and the default communications device. 

Perhaps this already exists and I've simply missed it?

**Comment by jholl016** [comment]
I second this request!  I'd love to see this offer get/set functionality for the default communications device.

**Comment by frgnca** [comment]
I can confirm the current version doesn't support this feature. But I'm pretty sure it could be done rather easily. I'll try to code a bit this weekend and update here when I've got something.

**Comment by frgnca** [comment]
I added the branch dev_v3.0.1_communicationdevice with pull request #30
