### ISSUE TITLE
Set RootModule node in psd1 to 'AudioDeviceCmdlets.dll' in published module

### ISSUE THREAD

**Issue by cdhunt** [frgnca/AudioDeviceCmdlets#20]
VIA User mmuffins sends the following message to the owners of item 'AudioDeviceCmdlets'.

Hi there, I just downloaded version 3.0.0.2 of AudioDeviceCmdlets because I wanted to control the audio volume from powershell. Awesome work, it really saved me the effort of writing something like that myself!

I noticed that no cmdlets are exported after installing the module from the gallery. I was able to fix it locally by changing #RootModule = '' to RootModule = 'AudioDeviceCmdlets.dll' in AudioDeviceCmdlets.psd1. It would be great to see a fix for this.

BR, Michael

**Comment by frgnca** [comment]
This should now be resolved in v3.0.0.4 available from the PowerShell Gallery. Don't hesitate to open a new issue. Thank you
