### ISSUE TITLE
Can you add the single-line command syntax for toggling mute to the help file examples?

### ISSUE THREAD

**Issue by ibex-are-goats** [frgnca/AudioDeviceCmdlets#27]
For example, I thought it might be "Get-AudioDevice -Recording | Set-AudioDevice -RecordingMuteToggle" to mute my microphone. But I have the syntax wrong. Would help to add the single-line shortcut trickery to the help. Thanks!

**Comment by frgnca** [comment]
```powershell
Set-AudioDevice -RecordingMuteToggle
```
This line alone will toggle the default recording device's mute state. When yo say "the help" do you mean the README.md file? Because the project would be in need of an official PowerShell help file.
