### ISSUE TITLE
Download link in site outadated

### ISSUE THREAD

**Issue by madprops** [frgnca/AudioDeviceCmdlets#29]
https://www.automatedops.com/projects/windowsaudiodevice-powershell-cmdlet/

**Comment by frgnca** [comment]
Thank you for the information, but this is an old post I do not have control over. I suggest people refer to the download link in the current README.md file. If in doubt, it is also possible to download the cmdlet from the PowerShell Gallery.
```PowerShell
Install-Module -Name AudioDeviceCmdlets
```

**Comment by cdhunt** [comment]
@madprops I'll update the original post to reference @frgnca as the new owner and the module's new location.
