### ISSUE TITLE
get-audiodevice -recording only returns one recording device when multiple are present

### ISSUE THREAD

**Issue by meadcd** [frgnca/AudioDeviceCmdlets#34]
When using "Get-Audiodevice -recording", cmdlet returns a single device which is set as the default.

using get-audiodevice -list | where-object {$_.Type -like "Recording"} returns all devices which are of type recording. Is this intended behavior?

**Comment by frgnca** [comment]
Yes this is intended behavior. The reason, if I remember correctly, is that in the past there were both a Get-DefaultPlaybackAudioDevice and a Get-DefaultRecordingAudioDevice cmdlets. Those became the -Playback and -Recording parameters of the Get-AudioDevice cmdlet.
