### ISSUE TITLE
Commands not working when moving script files

### ISSUE THREAD

**Issue by Shalashanka** [frgnca/AudioDeviceCmdlets#37]
Hello everyone,

thank you for the work on this commands, they really helped me in a personal project.

I'm noticed an issue however, i created a script .ps1 file and it's working fine.
However if i copy the ps1 file to another location and try to run it everything works except for the AudioDeviceCmdlets.
It's not giving me any errors, they just don't work(the Set-Audio device in particular).

**Comment by profound-killah** [comment]
Can you provide the code?

**Comment by Shalashanka** [comment]
Unfortunately i was working on the project more than one year ago, i eventually ended up scrapping it, sorry.
