### ISSUE TITLE
Feature request?

### ISSUE THREAD

**Issue by DTG123** [frgnca/AudioDeviceCmdlets#38]
I have very limited knowledge of POSH, so is it possible to toggle the default communication device ( headset) to out put to both the default speakers and the headset at the same time. 

if thats not possible, how would create a desktop shortcut to activate separate devices, right now the only way i know is togo into windows and set default device to the headset or desktop speakers manully

**Comment by frgnca** [comment]
> [...] to out put to both the default speakers and the headset at the same time

I might be mistaken, but no I do not think this is possible. At least not within the scope of how AudioDeviceCmdlets is currently coded. Sorry about that.
