### ISSUE TITLE
Request: disable a device

### ISSUE THREAD

**Issue by falcorr** [frgnca/AudioDeviceCmdlets#40]
I'm looking for the same functionality as Windows 10 Settings > System > Sound > Manage sound devices > [disabling a device]. 

This is for the use case of disabling the Nvidia output device used by Nvidia Gamestream / Moonlight. The effect is that of restoring sound to the server / PC while the stream continues (and re-enabling the device reverses the effect). This being the best method of (somewhat) disabling Moonlight from the PC and not the client, as currently required.

**Comment by TheMasterDingo** [comment]
I too would like this feature!

**Comment by frgnca** [comment]
I do intend to add support for enabling/disabling AudioDevice. I will refer further discussion to issue #21
