### ISSUE TITLE
Request: control microphone (eg. mute)

### ISSUE THREAD

**Issue by SpitFire-666** [frgnca/AudioDeviceCmdlets#42]
Would be awesome to have the ability to mute the microphone.

Currently I either have to do it via GUI (fiddly) or have access to the laptop keyboard and hit an awkward key combo. There's also no quick/easy way to check if it's muted within Windows.

Thanks

**Comment by dakota-mewt** [comment]
Hi, I have a project that utilizes AudioDeviceCmdlets to do exactly what you are suggesting. The project (Mewt)  interfaces with a physical button and an RGB LED via microcontrollers (Arduino, MicroBit) for the control and status feedback. 

https://github.com/dakota-mewt/mewt

**Comment by frgnca** [comment]
> Would be awesome to have the ability to mute the microphone.

It should be possible with the following command 
```PowerShell
Set-AudioDevice -RecordingMute $true # Sets the default recording device's mute state to the given <bool>
```
