### ISSUE TITLE
Get-AudioDevice : Parameter set cannot be resolved using the specified named parameters.

### ISSUE THREAD

**Issue by lennartboorsma** [frgnca/AudioDeviceCmdlets#46]
Hi,

Seems that the cmdlet is not function well anymore. Can you tell whats the problem?

It's on a Windows 10 1909 Enterprise OS with latest secuirity patches. Also on 20H2 it doesnt work. 

Get-AudioDevice : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AudioDevice
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AudioDevice], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,AudioDeviceCmdlets.GetAudioDevice

**Comment by frgnca** [comment]
This error is normal behavior. Please see the Usage section of the README.

To be able to work, the Get-AudioDevice cmdlet needs to receive a parameter like
```PowerShell
Get-AudioDevice -List
```
or maybe an index number like
```PowerShell
Get-AudioDevice -Index 1
```

These should not end in error.  
Hope this helps, have a nice day.
