### ISSUE TITLE
The module does not install

### ISSUE THREAD

**Issue by kaiserdj** [frgnca/AudioDeviceCmdlets#49]
I have tried it in various ways and it does not install

![image](https://user-images.githubusercontent.com/5487950/149156314-42ff7800-7040-406e-9c20-26781e710c8e.png)

**Comment by Eloi-Perez** [comment]
Try Import-Module AudioDeviceCmdlets

**Comment by Eloi-Perez** [comment]
I'm using `Import-Module AudioDeviceCmdlets` at the start of my script to make it work.

**Comment by kaiserdj** [comment]
I do not understand why yesterday it was not installed and today if .....
It may be that having windows 11 insider and it has been updated something has changed ...
Sorry for the bother, now it works for me
