### ISSUE TITLE
Get-AudioDevice -PlaybackCommunication 

### ISSUE THREAD

**Issue by LonleyViper** [frgnca/AudioDeviceCmdlets#57]
I get the following error with this:

```
`Get-AudioDevice : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AudioDevice -PlaybackCommunication
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AudioDevice], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,AudioDeviceCmdlets.GetAudioDevice`
```

Any help would be appreciated :D

**Comment by LonleyViper** [comment]
Okay I realise it's because I have the old version installed. I cannot uninstall it for some reason... even when I delete the module folder I cannot install the new version. It always reverts to the old version. Anyone able to help?

**Comment by LonleyViper** [comment]
Managed to uninstall with the below. I see now that the "release" DLL isnt the latest version from this branch....DOH

```
$modulePath = "<path>"
if (-not (Test-Path $modulePath)) {
    "There is no AudioDeviceCmdlets folder in $modulePath, doing nothing."
    break
}

takeown /F $modulePath /A /R
icacls $modulePath /reset
icacls $modulePath /grant Administrators:'F' /inheritance:d /T
Remove-Item -Path $modulePath -Recurse -Force -Confirm:$false
```

**Comment by LonleyViper** [comment]
Ive built it from source now and it works.

Thanks!

**Comment by frgnca** [comment]
Thank you @LonleyViper for taking the time to write this up, as I feel it might help others.
