### ISSUE TITLE
Doesnt list Bluetooth Audio devices

### ISSUE THREAD

**Issue by mkanet** [frgnca/AudioDeviceCmdlets#7]

**Comment by cgrace70** [comment]
Anything to report on this?  I just started using a Bluetooth speaker with my laptop.   :)

**Comment by cdhunt** [comment]
I have no plans to implement this at the moment.

**Comment by frgnca** [comment]
@mkanet @cgrace70 could you confirm if you can now list bluetooth audio devices? I was able to list mine. They have to be connected, not just paired.

**Comment by mkanet** [comment]
@frgnca I dont have my development PC available.  Could you please upload the latest pre-built dll to Github.  I've been happy to try.

**Comment by mkanet** [comment]
@frgnca I can confirm I can list bluetooth audio devices using the latest dll.  I can now control these bluetooth devices using your cmdlets.  Thanks!!
